### ISSUE TITLE
Controlled react input moves caret to the end of the entered text

### ISSUE THREAD

**Issue by StasPerekrestov** [reflux/refluxjs#101]
When a controlled input is used and it's bound to a Reflux store, then caret always moves to the end of the entered text.
It makes hard to edit the text in the middle.

demo project
https://github.com/StasPerekrestov/reflux-qa

controlled input sample can be found here
https://github.com/StasPerekrestov/reflux-qa/blob/master/public/js/q-editor.js

**Comment by bsingr** [comment]
Works for me. Can we document this somewhere?
