### ISSUE TITLE
Ambiguous docs / usage for Component -> Store listeners

### ISSUE THREAD

**Issue by damassi** [reflux/refluxjs#105]
I'm testing out Reflux as a way to simplify my React flow and I'm finding that the docs are somewhat ambiguous about how to best listen to store updates in react components.  

In the Store example you provide, its a fairly clear and explicit one-to-one which maps to the common addEventListener(event, method) pattern:

```
var Store = Reflux.createStore({
    init: function() {
        this.listenTo(actions.fireBall,this.onFireBall);
        this.listenTo(actions.magicMissile,this.onMagicMissile);
    },
    onFireBall: function(){
        // whoooosh!
    },
    onMagicMissile: function(){
        // bzzzzapp!
    }
});
```

But within the Component it is not so clear, and the docs provide no further clarification of the conventions that you're using:

```
// Fairly simple view component that outputs to console
function ConsoleComponent() {

    // Registers a console logging callback to the statusStore updates
    statusStore.listen(function(status) {
        console.log('status: ', status);
    });
};
```

and 

```
var Status = React.createClass({
    mixins: [Reflux.ListenerMixin],
    onStatusChange: function(status) {
        this.setState({
            currentStatus: status
        });
    },
    componentDidMount: function() {
        this.listenTo(statusStore, this.onStatusChange);
    },
    render: function() {
        // render specifics
    }
});
```

What happens if the store that the component is listening to has multiple methods?  Did you design Reflux to only support one store method per component?   From the above it looks like the mixin is magically connecting events to methods created without explicit intent where the normal pattern (say, with Backbone) is `this.listenTo(model, event, method)`.  The above examples could be written like so, which would be much clearer in terms of intent.  

Lastly, here's a better illustration of the problem:

```
var CommentComponent = React.createClass({
  mixins: [Reflux.ListenerMixin],

  componentDidMount: function () {

    // Problem 1:  
    // How do you discern the difference between onFetchComments 
    // and onPostComments? Right now our component is just listening
    // to the CommentStore and lots of stuff might be going on.  When
    // onFetchComments is called, so is onPostComment because it gets
    // confused.  How did you envision we should listen to multiple events?

    this.listenTo(CommentStore, this.onFetchComments);
    this.listenTo(CommentStore, this.onPostComment);

    // Problem 2:  
    // This is a better implementation, but it breaks if the user is making
    // any sort of async ajax request in the store as it appears to bypass the store completely.  
    //  I cant figure out if there's something going on in
    // my code or if there is a bug in the codebase, or if I'm just misunderstanding completely.

    this.listenTo(CommentAction.fetchComments, this.onFetchComments);
    this.listenTo(CommentAction.onPostComment, this.onFetchComments);
  },

})

```

Another thing that would be nice is if you had actual API docs as opposed to just usage examples.  Like... when you include the `Reflux.ListenerMixin`, what methods does it supply to the Component?  What is the method signature for `this.listenTo`?.

**Comment by marconi** [comment]
But what happens say on the store you send an ajax request to save the comment, when something goes wrong how do you notify the component with error message?

**Comment by krawaller** [comment]
There are several approaches to tackle that. One way would be to have the store call a "commentsavefailed" action which the component is listening to. If it is a more complex app I sometimes have an "errorStore" which listens to error actions called by other stores, and then my component(s) listen to the errorStore.

**Comment by marconi** [comment]
Thanks @krawaller, yeah ended up with response specific actions which indicates if its success or not.
