### ISSUE TITLE
Use a message bus driven architecture

### ISSUE THREAD

**Issue by Kasu** [reflux/refluxjs#110]
[I have an issue with the Reflux event handling architecture](https://github.com/spoike/refluxjs/issues/109).

None of these problems are necessary and can be solved in Reflux by adopting a message bus driven architecture and allowing the user to customize event behavior like order of execution and synchronicity themselves, with the only breaking change that Reflux.setEventEmitter will be deprecated.

What we need to change is to interface with a single application wide message bus instance instead of a unique event emitter per action.

#### Example: createAction.js

```javascript
var PublisherMethods = require('./PublisherMethods');
var MessageBus = require('./MessageBus.js'); 
// Note: Let users customize the message bus instance via 
// Reflux.setMessageBus, instead of a type with setEventEmitter

function createAction (name) {
    var functor = function () {
        // Let the bus completely decide how emitting is performed.
        // For even better control, we pass in the whole functor as context data.
        return MessageBus.emit(functor, arguments);
    };
    functor.name = name;  // Store event name as context data
    extend(functor, PublisherMethods);  // PublisherMethods also interfaces with MessageBus
    return functor;
}

module.exports = createAction;
```
> Note that we must update publisher/listener methods to interface with the message bus too.

The message bus now owns all the event logic, enabling any users like myself control the order of execution and synchronicity without modifying Reflux. 

> We can easily implement a message bus that maintains the event logic Reflux currently have.

#### What is a message bus?

A message bus basically provides the same interface as an event emitter, with the one exception that it's an instance and not a type to be instantiated per action (although I would personally vouch for a subscription based interface over a listener interface). This way the bus may store state if it so wishes, controlling things like order of execution or synchronicity. 

> For instance, we could implement a message bus that works like [facebooks Dispatcher](https://github.com/facebook/flux/blob/master/src/Dispatcher.js), for those you wants to further align with the Flux architecture.

Also, instead of emitting only an event name, we may extend the contract by passing in a context hash (the action functor) to the event emitting function of the message bus, where the name is just a property among many others. This gives the message bus even more control and flexibility. For instance, the Reflux specific "sync" property can be handled so that synchronicity can be controlled per action by customization. Or a channel property could be added, [for those who want such an architecture](https://github.com/spoike/refluxjs/issues/19).

Please let me know what you think about this!

**Comment by spoike** [comment]
I believe @LongLiveCHIEF is working on something like this in 0.3.x. So I'm culling this issue.
