### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by echenley** [reflux/refluxjs#128]
I noticed errors leave behind raw stack traces which are often quite opaque. One such case I came across was this:

``` javascript
    mixins: [
        Reflux.listenTo(postStore, 'onPostChange')
    ],
```

If `this.onPostChange` is not defined, the stack trace is something like:

```
Uncaught TypeError: undefined is not a function   PublisherMethods.js:36
  eventHandler                                    PublisherMethods.js:36
  emit                                            index.js:73
  module.exports.trigger                          PublisherMethods.js:52
  Reflux.createStore._updatePosts                 postStore.js:25
  .
  .
  .
```

Something as simple as "onPostChange is undefined" would be a huge improvement.

**Comment by BryanGrezeszak** [comment]
With new syntax, the specific example isn't relevant anymore, and otherwise as a general concept I think it's a little too vague to have as an issue. Improvements in error messages can be handled individually as they are recognized and pointed out.
