### ISSUE TITLE
connect mixin with immutable-js is broken

### ISSUE THREAD

**Issue by ruswerner** [reflux/refluxjs#163]
If you are using https://github.com/facebook/immutable-js/ in your stores, and you trigger out ```Immutable``` instances, then if you also use the ```connect``` mixin on your React components, it will convert your immutable instance into a plain JS object.

Line 17, from ```connect.js```

    var me = this, cb = (key === undefined ? this.setState : function(v){me.setState(_.object([key],[v]));});

uses ```setState``` which merges the triggered data into the state, but in this case, since an immutable instance is being used, it doesn't work and isn't desired. In this case, it should use ```replaceState```, and then you can also use ```Immutable.is()``` in the ```shouldComponentUpdate()``` to optimise rendering.

Ideally, I would like a separate mixin that uses ```replaceState```, or as an option to the mixin.

Is anyone else in the Reflux community using immutable-js in their stores? If so, how are you getting around this? In the meantime, I have to convert immutables to plain JS when triggering. So there are lots of ```this.trigger(this.data.toJS());``` everywhere. No ideal, but maybe this is the correct approach?... keep the immutable ops in the store...

Cheers.

**Comment by spoike** [comment]
This has moved to #340
