### ISSUE TITLE
Store render-like method

### ISSUE THREAD

**Issue by azproduction** [reflux/refluxjs#174]
The common pattern of using Store is:

``` js
this.data = update(this.data);
this.trigger(this.data);
```

which is speaking in React's terms is `setState` and `render`. But in the same time Store's render is splitted along Store's action handlers, which could be a point of failure. Or one eventually defines that "render" method: [example](https://github.com/spoike/refluxjs-todo/blob/master/js/store.js#L57-L61)

``` js
var store = Reflux.createStore({
    onActionA: function() {
        this.list = [];
        // (!) render version 1
        this.trigger(this.list)
    },
    onActionB: function() {
        // It masks state update
        this.list.push('value');
        // (!) render version 2
        this.trigger(this.list.join(','));
    },
    getDefaultData: function() {
        this.list = [];
        return this.list;
    }
});
```

I think we should make Store strict in order to follow React's rendering pattern as Store itself is a View, but for data. And view which returns consistant data is common pattern and chaotic or random data type is not.

``` js
var store = Reflux.createStore({
    onActionA: function() {
        // (1) state modification
        this.setState({
            list: []
        });
    },
    onActionA: function() {
        // (2) state modification
        this.setState({
            list: this.state.list.concat('value')
        });
    },
    getDefaultData: function() {
        return [];
    },
    // (3) render-like method, but for data
    emit: function() {
        return this.state.join(', ');
    }
});
```

Benefits:
- Single data renderer
- Easy to find all state change points

PS I know that one can extend reflux.Store with mixins and implement such pattern, but I thought that It is good to have it in a "standard library".

**Comment by spoike** [comment]
:+1:

**Comment by willembult** [comment]
:+1: I use stores this way. However, I keep my store data in a private variable outside of the store, to prevent outside access, rather than in a property on the store.

```javascript
var data = {}; //private, not exposed

module.exports = Reflux.createStore({
    onActionA: function(res) {
        data[a] = res;
    },

    getA: function() {
        return data[a];
    }
});
```
I like doing it this way because it reduces the risk of store modifications without using the single-directional data flow using actions. I like to make the model as easy as possible to follow, and as hard as possible to break. Could we achieve this and still have a forced setState interface for the action handler methods?

**Comment by gpbl** [comment]
@willembult how would you rehydrate a store (for server side rendering) if you put data in a private variable?

**Comment by ivan-kleshnin** [comment]
What @azproduction says is wise and true. :+1:

**Comment by srph** [comment]
:+1:
