### ISSUE TITLE
Reflux.connect not updating state for mounted component

### ISSUE THREAD

**Issue by fk1blow** [reflux/refluxjs#226]
I am using Reflux.connect to sync the store with the component. Ok, everything works fine until
i add an async operation inside the store. 

If i update the store state(this.trigger(storeData)) before the component was mounted,
the state of the component is the correct/expected one. If i mount the component, then
update the store(this.trigger(storeData)), the expected value will be incorrect.

Is the Reflux.connect working in ways that i cannot seem to understand properly? Do i need
to use this.listenTo(store) for this kind of operations?

**Comment by pstadler** [comment]
Same problem here. Needed to do a workaround using `ListenerMixin`.

**Comment by jeffdonthemic** [comment]
I'm encountering this same issue as well. I used ListenerMixin to work around it.

**Comment by spoike** [comment]
This sounds a little bit like a problem another user had, which was due to [the wrong data being sent from `getInitialState`](http://stackoverflow.com/questions/29308672/reflux-trigger-wont-work-without-a-delay-in-init/29384412#29384412).

Do you have any code example that reproduces this?

**Comment by jeffdonthemic** [comment]
Here's the [store's init](https://github.com/jeffdonthemic/react-banners-salesforce/blob/master/src/scripts/stores/bannersStore.js#L14) and the [view component](https://github.com/jeffdonthemic/react-banners-salesforce/blob/master/src/scripts/components/banners.js#L12). If I return the same objects synchronously, it works like a champ.

**Comment by Dharmoslap** [comment]
Happens to me as well.

**Comment by ecastano** [comment]
Thanks @jeffdonthemic! I was running into the same issue.... your workaround helped me out.

**Comment by promethe42** [comment]
I have the same issue. Any progress on this?

**Comment by BryanGrezeszak** [comment]
Spoike asked for a code example to reproduce the issue, and seeing as nobody has given one in over a year and a half I'm gonna consider this not an active issue any more. If you have a similar issue, post it new and please include minimal code possible to reproduce.
