### ISSUE TITLE
Something between connect and listenTo?

### ISSUE THREAD

**Issue by flying-sheep** [reflux/refluxjs#238]
Hi,

`connect` is the ultimate convenience thing if you just want to mutate state anyway.

`listenTo` can do anything, but is not coupled to a certain state variable.

i often want to use both convenience functions, i.e. Store.getInitialState as well as automatic assignment to some state variable, but still do something custom.

therefore, i’d like something like this API:

``` js
Reflux.connect(listenable[, stateName][, callback])
```

where `callback` would be a processing hook, specified as function or method name (like in `listenTo`)

it receives the argument of `listenable.trigger(someArg)` (again like `listenTo`).

if it returns `undefined`, `someArg` is assigned to `stateName`, or, if `stateName` isn’t specified, `setState(someArg)` is called.

if it returns some `retVal`, `retVal` instead of `someArg` is used the same way.

example:

``` js
var MyStore = Reflux.createStore({
    val: 'foo',
    init() {
        this.listenTo(Actions.myAction, this.setVal)
    },
    setVal(val) {
        this.val = val
    },
    getInitialState() {
        return this.val
    },
})

//once MyStore triggers, do setState({myVal: MyStore.val + ' bar'})
var Alt1 = React.createClass({
    mixins: [
        Reflux.connect(MyStore, 'myVal', 'valHook')
    ],
    valHook(val) {
        return val + ' bar'
    },
    render() { ... },
})

//once MyStore triggers, do setState({otherVal: MyStore.val + ' bar', myVal: MyStore.val})
var Alt2 = React.createClass({
    mixins: [
        Reflux.connect(MyStore, 'myVal', 'valHook')
    ],
    valHook(val) {
        this.setState({
            otherVal: myVal + ' baz',
        })
        //no explicit return: reuse val
    },
    render() { ... },
})
```

the only problem is that both non-listenable arguments can be strings, so if only listenable and one string are given it’s ambiguous if it’s a callback or state name…

**Comment by BryanGrezeszak** [comment]
With mixins not being a main focus anymore this doesn't seem relevant. I'm closing this unless someone has something else to say on it.
