### ISSUE TITLE
connect() should use replaceState()

### ISSUE THREAD

**Issue by Turbo87** [reflux/refluxjs#242]
https://github.com/spoike/refluxjs/blob/master/src/connect.js#L17 should be changed to use `replaceState()` instead of `setState()`.

If my store has data `{a: 5, b: 10}` and the data changes to `{a: 5, c: 15}` the state of the connected components will now be `{a: 5, b: 10, c: 15}`. I consider this a bug since I expected the `connect()` function to always sync the store data with the component state.

**Comment by confiks** [comment]
The function to create a `connect` mixin has the signature `connect(listenable, key)`. If you specify a key, `this.state[key]` of the component will contain exactly the contents of the last trigger of your store.

By using `replaceState`, one could only listen to a single store. It might make some sense when `connect` is called without key, but I don't find the use-case convincing.

**Comment by Turbo87** [comment]
@confiks you are right about that. I only noticed that issue when I used a single store connection. As you can see in #243 I already changed my suggestion to only use `replaceState()` if no `key` is specified.

**Comment by devinivy** [comment]
As of React 0.13.0 `replaceState()` is deprecated, at least from ES6 classes (more at https://github.com/facebook/react/issues/3236).  According to #243 Reflux's trajectory here is to deprecate keyless use of `Reflux.connect()`, which has an issue here #340.
