### ISSUE TITLE
Can't have other property 'hasListener' when using Reflux.listenTo!

### ISSUE THREAD

**Issue by jvmlet** [reflux/refluxjs#245]
I get this exception when I use both Reflux.ListenerMixin and  Reflux.listenTo(store, "onChange") mixins :
````javascript
    React.createClass({
    mixins: [Reflux.ListenerMixin, Reflux.listenTo(myStore, "onChange")],
    })
````
Please advise.
Thanks
Alexander

**Comment by spoike** [comment]
@jvmlet: What is the exception?

**Comment by jvmlet** [comment]
The exception is "Can't have other property 'hasListener' when using Reflux.listenTo!"

**Comment by spoike** [comment]
Please don't use Reflux.ListenerMixin together with Reflux.listenTo.
