### ISSUE TITLE
ListenerMixin not working correctly

### ISSUE THREAD

**Issue by Turbo87** [reflux/refluxjs#246]
I'm using Reflux v0.2.5 and React v0.12.2 roughly like this:

```js
React.createClass({
    mixins: [Reflux.ListenerMixin],

    componentDidMount() {
        this.listenTo(Store, this.replaceState);
    },

    render() {
        // ...
    }
});
```

but is seems that the ListenerMixin is not doing its job properly as I get the following error in the Chrome console:

> Uncaught Error: Invariant Violation: replaceState(...): Can only update a mounted or mounting component.

The error disappears when I replace `this.replaceState` with something like this:

```js
state => {
    if (this.isMounted())
        this.replaceState(state);
}
```

**Comment by spoike** [comment]
Yes, it's a bug. Not sure if it is on React's side or not since `componentDidMount` should sensibly by it's name sake have a mounted node ready. There is a PR for this. #239

**Comment by Turbo87** [comment]
I think #239 (similar to my workaround) only hides the error message without actually fixing the problem. We should rather find out why the mixin is not unsubscribing properly, otherwise this might lead to e.g. memory leaks.

**Comment by devinivy** [comment]
#239 was merged and released some time back.  We're now revisiting the issue in #393, as `isMounted()` is deprecated.
