### ISSUE TITLE
An Architecture idea - adding model to Store, totally hiding actions, and getting closer to React

### ISSUE THREAD

**Issue by yonatanmn** [reflux/refluxjs#334]
In order to hide the Actions in Reflux, I propose that they will be auto created and auto triggered, moving the responsibility to the listeners (React Components or other Stores).

I think about adding to each store a property called `model`. e.g. inside `AnimalsStore`, there will be a `model:{cats:3,dogs:5}`. then the store methods could call `setModel({cats:4})`, 
with every `cats` call (or only when changed) an hidden action will be triggered, using @jesstelford's [triggerables mixin](https://github.com/jesstelford/reflux-triggerable-mixin) (see [discussion](https://github.com/spoike/refluxjs/issues/158)) and a Component could do : `this.listenTo(AnimalsStore.cats, handleCatChange)`.

This is quite similar to React `setState()` idea of calling render for every change, and if one will work with this strictly, no more explicit `trigger`.  This will also provide a visible model for each store separating it to a sort of MV*, 

What do you think? should I try to implement this?

**Comment by oriSomething** [comment]
it seams a bit something that makes things more complicated. maybe if you write some code for demo, it would be clearer.
i made a decorator, that subscribe component to store changes to `setState` and the store always trigger an object literal with the name / symbol of the store (example: `{ storeName: ... }`). it makes it simpler to me

**Comment by yonatanmn** [comment]
@oriSomething - here's what I meant:
[reflux-state-mixin](https://github.com/yonatanmn/reflux-state-mixin),

**Comment by spoike** [comment]
This is now optional through @yonatanmn's mixin, and documented in the README.
