### ISSUE TITLE
Ability to listen to a react-router store for URL changes?

### ISSUE THREAD

**Issue by mrcoles** [reflux/refluxjs#336]
I can’t find a clear solution online for how someone should listen to URL / router changes (especially for dynamic segments) in a reflux + react-router + react application. I’d like there to be a way to create some sort of “store” out of a package like react-router so I can then listen to it in other stores and trigger updates to my react components when necessary.

A lot of people appear to be building reflux + react-router + react applications. While handling static segments it’s pretty straightforward, however, with dynamic segements the web has a mess of answers on how to do this, most including using hacky, error-prone approaches of using react methods like “componentDidMount”, “componentDidUpdate”, “willTransitionTo”, etc. For example, see the react-router docs section titled [Important Note About Dynamic Segments](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#important-note-about-dynamic-segments). Given the declarative, render-a-snapshot-of-the-data functionality of react components, IMO they should *not* be responsible for triggering these changes.

Is there a clean way to tie in react-router changes with the action -> store flow of reflux?

**Comment by mrcoles** [comment]
I just spent a little more time looking at it and thinking about it (maybe I’m just rubber duck debugging :smirk:), and have two positive things to add.

First, the react-router guide that I linked to is no good, anyone trying to use react-router should use the full [react-router documentation page](http://rackt.github.io/react-router/) (which I somehow overlooked on their main README).

Second, here’s an approach I’m now using to try to make things play well with reflux and to avoid hacky state update methods in the react components.

In my component file for the router, trigger an event named “route” that has the important information about the current route (including the name).

```javascript
ReactRouter.run(routes, function (Handler, state) {
    React.render(<Handler />, document.getElementById('ui-main'));

    var curRoutes = this.getCurrentRoutes();
    var route = curRoutes[curRoutes.length - 1];
    Actions.route({
        name: route.name,
        names: curRoutes.map(function(route) { return route.name; }),
        params: this.getCurrentParams(),
        path: this.getCurrentPath(),
        pathname: this.getCurrentPathname()
    });
});
```

The above assumes I have an actions object named `Actions`, so I added an action named “route”  to those. Something like…

```javascript
window.Actions = Reflux.createActions({
    // route
    route: {},
    …
});
```

And then in any of my stores that listen to `Actions`, I can listen for that route action and trigger a handler like the following hypothetical user page handler:

```javascript
        onRoute: function(data) {
            if (data.name === 'user') {
                this.data.userId = data.params.userId;
                this.trigger(this.data);
            }
        }
```

The main step is creating a meaningful enough data object for the `route` action inside the `ReactRouter.run` callback.

How does this approach look?

**Comment by devinivy** [comment]
This approach looks good to me!  Ideally the route change should be converted into an action, just as you've done :)

@LongLiveCHIEF I don't see what enhancement to refluxjs or reflux-core is implied by the label here, but if I'm mistaken, we can certainly reopen.

If there's any more discussion to be had here, definitely open an issue over on our discuss repo: https://github.com/reflux/discuss
