### ISSUE TITLE
store state mixin (with state triggerables)

### ISSUE THREAD

**Issue by yonatanmn** [reflux/refluxjs#358]
Hi,
Just uploaded [reflux-state-mixin](https://github.com/yonatanmn/reflux-state-mixin), take a look.

it enables stores to have state, setState(), and getInitialState(), and creates an hidden action out of every state key. 

Inspired by [this](https://github.com/jesstelford/reflux-triggerable-mixin/blob/master/src/index.js), and [this](https://github.com/spoike/refluxjs/issues/290). Originaly had the idea [here](https://github.com/spoike/refluxjs/issues/334)

**Comment by spoike** [comment]
This is now documented in the README.

**Comment by yonatanmn** [comment]
Cool.
What about integrating this to reflux? 
It became quite popular:

NPM Stats:
519 downloads in the last day
4,157 downloads in the last week
15,247 downloads in the last month

**Comment by spoike** [comment]
@yonatanmn I'm thinking about implementing data contexts in reflux, so that actions and stores will be instantiated along with a data context. It might supersede reflux-state-mixin, not sure, but I'll see if I can revisit the mixin after that.
