### ISSUE TITLE
Should I emit an entire collection when a single object changes?

### ISSUE THREAD

**Issue by drewhamlett** [reflux/refluxjs#384]
Right now I have something like this.

```js
const Store = Reflux.createStore({
  listenables: Actions,

  getInitialState() {
    this.surveys = []; // loaded from server via an action
  },

  onCreateNote(surveyId, note) {
    const index = _.findIndex(this.surveys, { id: surveyId });
    const request = $.post('/api/surveys/notes.json', {
      note: note,
      surveyId: surveyId
    });

    request
      .success((survey) => {
        this.surveys[index] = survey;
        this.trigger(this.surveys);
      });
  }
});
```

```js
@mixin.decorate(Reflux.listenTo(Store, 'onSurveysChange'))
class Surveys extends React.Component {

  onSurveysChange(surveys) {
    this.setState({
      surveys: surveys
    });
  }

}
```

So the surveys table is rendered and then each survey is rendered.  The row has an option to write a note.  So I create the note and then re trigger the entire survey collection.  Should I have a store for each individual survey or one for the entire collection like I'm doing now?

Thanks for the help

**Comment by clintwood** [comment]
This is a good question and I'd be interested in the answer to this too... Maybe this is a better question for the reflux slack channel so if you post there I'd be interested in hearing what people say!

**Comment by spoike** [comment]
Please use the following communication channels as they are a better forums for questions:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful][thinkful-image]][thinkful-url]
