### ISSUE TITLE
React ES6 components do not support mixins

### ISSUE THREAD

**Issue by mattotodd** [reflux/refluxjs#386]
Are there any plans to add some of mixin functionality for use with ES6 components? Either through composition or inheritance? 

It seems react is [not going to support mixins](https://facebook.github.io/react/docs/reusable-components.html#no-mixins) going forward

**Comment by LongLiveCHIEF** [comment]
Yes-ish. Step one, which the latest release has already implemented, is to completely separate reflux from React. Step 2, is to build a plugin interface for Reflux. Step 3 would be to build a plugin that is a "Reflux" component.  See these conversations:

https://github.com/reflux/refluxjs/issues/293
https://github.com/reflux/refluxjs/issues/380
