### ISSUE TITLE
Warning: isMounted(...)

### ISSUE THREAD

**Issue by Asgator** [reflux/refluxjs#393]
Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

How to remove?

**Comment by spoike** [comment]
I'll see if we can remove the isMounted calls for the next release.

**Comment by Asgator** [comment]
Thx :)

**Comment by Asgator** [comment]
Hello, Is it possible to solve this problem?

**Comment by spoike** [comment]
Sorry, I'll see if I can fix it for next release. Priority was getting React 0.14 support up and running, and fixing the CSP issue with eval in reflux-core.

**Comment by daGrevis** [comment]
:+1:

**Comment by devinivy** [comment]
Reviewing PR #445.

**Comment by devinivy** [comment]
Closed by #445.
