### ISSUE TITLE
Add version to reflux object

### ISSUE THREAD

**Issue by rmilesson** [reflux/refluxjs#394]
Hey, I'm working on a older system with an unknown version of reflux which makes it kinda hard to debug stuff.
Is it possible to add a version-property to the reflux object to avoid this problem? Alternatively a banner in the disted files.

On the same note, is it possible to determine version some other way I don't know about? ;)

**Comment by spoike** [comment]
reflux-core exposes a version number, haven't added it into the refluxjs build yet though. It is in `Reflux.version` object. Obviously old versions do not expose this, you have to check the package.json file if you have it.

**Comment by rmilesson** [comment]
Can't find the `package.json`, oh well, I'll just upgrade. Thanks for your time :)
