### ISSUE TITLE
shouldComponentUpdate can't receive the newest props or state

### ISSUE THREAD

**Issue by YikaJ** [reflux/refluxjs#396]
I use `Reflux.connect` or `listenTo` methods to change component state, but I can't get the different part in `shouldComponentUpdate` between `nextProps` and `this.props` or state..., they look like the same!

what should I need to do, when I want to use `shouldComponentUpdate` in Reflux..

**Comment by YikaJ** [comment]
finally I had found that because of the reference type.....
so is there any help of trigger reference type？
I think _.cloneDeep() maybe too slow...

**Comment by LongLiveCHIEF** [comment]
For questions please use the following communication channels:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful][thinkful-image]][thinkful-url]

Please only use the [issue tracker](https://github.com/spoike/refluxjs/issues) for bugs and feature requests only.

**Comment by YikaJ** [comment]
I get it... 
I just found that Immutable.js maybe the solvtion
