### ISSUE TITLE
Remove `dist` from `.npmignore`

### ISSUE THREAD

**Issue by marsjosephine** [reflux/refluxjs#397]
The `dist` folder is no longer distributed with version `0.2.12` because the `dist` directory has been added to the [`.npmignore`](https://github.com/reflux/refluxjs/blob/master/.npmignore).

Should `dist` be removed from `.npmignore` so that projects `npm install`-ing `reflux` can use the files in `dist` as well?

**Comment by LongLiveCHIEF** [comment]
No. If you are using npm to install, then you'll need to transpile (browserify/webpack/babel/etc...) reflux with the rest of your commonJS modules if your target environment is something other than node.

Alternatively, if you don't want to transpile, you can run npm install on the module to create the `dist` yourself.

**Comment by spoike** [comment]
You really shouldn't be using the dist if you're transpiling to the browser. It has been the source of multiple browserify issues in the past and will most likely break in the future again. There are however three ways to get the dist folder:

1. Use the Bower version
2. Use the CDN version
3. Download the source tarball and use that
4. If you're adamant on using dist in reflux, you can as @LongLiveCHIEF describes, run `npm install` on the installed module at `./node_modules/reflux` to fetch all dependencies and build the dist with `npm run build`.
