### ISSUE TITLE
No dist folder in npm package since ec497c9ced8968405af3a89ec9d906012d03188f

### ISSUE THREAD

**Issue by FractalizeR** [reflux/refluxjs#399]
Hello.

This commit ec497c9ced8968405af3a89ec9d906012d03188f introduced a build issue into our system. Previously we just fetched `dist/reflux.js` or `dist/reflux.min.js` into our gulp system. Currently the whole `dist` folder is excluded from `npm`, so every reflux user is ought to build his own version of reflux. This seem to complicate things a bit.

Despite this being not an API change, it is still seen by me as a BC.

**Comment by spoike** [comment]
This has been discussed in #397.
