### ISSUE TITLE
correct way of doing ajax in actions listen and listenAndPromise

### ISSUE THREAD

**Issue by wuichen** [reflux/refluxjs#401]
Trying to do my ajax calls in actions and pass the result to the store. When there's internet connection, the code works perfectly and calls the complete method. However, when theres not, it shows Uncaught in promise as the picture showed without any error status code. The issue happens in both listen and listenAndPromise. I would like to know whats the error code if the call fails.

using listenAndPromise: 
```javascript
ReportActions.loadReport.listenAndPromise(function(count) {
    return $.ajax({
        type: 'GET',
        data: {count: count},
        url: 'http://localhost:8080/next'
    });
})
```
Using listen:
```javascript
ReportActions.loadReport.listen(function(count) {
    return new Promise(function(resolve, reject) {
        console.log("init promise")
        var request = $.ajax({
          url: "http://localhost:8080/next",
          method: "GET",
          data: { count : count }
        });
        request.done(function(res){
            resolve(res);
        });
        request.fail(function(jqXHR, textStatus){
            reject(Error(textStatus));
        })
    }).then(ReportActions.loadReport.completed).catch(ReportActions.loadReport.failed);
})
```

<img width="702" alt="screen shot 2015-08-19 at 12 22 27 pm" src="https://cloud.githubusercontent.com/assets/6353587/9366620/4f5bb9d8-466d-11e5-81d6-3bf7ee7ac285.png">

**Comment by LongLiveCHIEF** [comment]
This is not a reflux issue, it's an Ajax usagr/library thing. It's also not a bug.

**Comment by wuichen** [comment]
@LongLiveCHIEF  So how should I make calls to the server? Whats the proper way of doing so in react? Could you provide an example? What library do you recommend me to use for server calls?
 Thank you very much!
