### ISSUE TITLE
Reflux actions throw an error in the console when they fail

### ISSUE THREAD

**Issue by liady** [reflux/refluxjs#403]
Lately I started getting `Uncaught (in promise) some-error` errors in my console whenever an action failed.

I researched a bit and found out that Reflux creates a promise every time an action is triggered, and if the action fails, the promise rejects and there is no one to catch it. I boiled it down to:
```js
// create an action with completed/failed children
var action = Reflux.createAction({asyncResult:true});

// *** First scenario - throws error *** //
// invoke the action
action();
// somewhere the action has failed
action.failed("some reason"); // throws an error in the console - why??


// *** Second scenario - ok *** //
// invoke the action, but with a catch clause
action().catch(function(){});
// somewhere the action has failed
action.failed("some reason 2"); // this is now ok...
```
[Fiddle here](http://jsfiddle.net/oc4uvqtx/2/)

Seems like every action trigger creates a promise, and that causes this issue when the action fails. I would imagine this would happen only when calling `action.triggerPromise` explicitly, and not every time.

Currently I have to attach a `catch` clause to every action trigger in my code to fix this problem. I want my components to just call the actions, not handle their outcome. Is there a way to avoid it? Am I missing something here?

**Comment by jfairley** [comment]
:+1: 

I would like to see this resolved as well. If a developer wants to log an error, they can do so with an `onActionFailed` function. IMO, reflux should remain silent.

**Comment by CrisLi** [comment]
+1

**Comment by CrisLi** [comment]
Is there any plan which release will have this bug fixing?

**Comment by spoike** [comment]
Since reflux-core (and by extension reflux) has had it's promise extensions extracted to [reflux-promise](https://github.com/reflux/reflux-promise). I've moved the issue there: reflux/reflux-promise#4
