### ISSUE TITLE
Jest unit test reflux store?

### ISSUE THREAD

**Issue by feketegy** [reflux/refluxjs#407]
Can somebody please write a concrete example on how to unit test reflux data stores using jest?

What I have so far:

```js
// Store
var actions = require('../actions/actions');
var Reflux = require('reflux');

var ValidationService = Reflux.createStore({

	listenables: actions,

	onValidateAnswer: function( options )
	{
		console.log('on validate answer function');
	}
});

module.exports = ValidationService;


// Store test
jest.autoMockOff();
jest.mock('../Validation');

describe('Validation', function() {

	var actions, validationService;

	beforeEach(function() {

		actions = require('../../actions/actions');
		validationService = require('../Validation');

	});

	it('tests something', function() {

		actions.validateAnswer({
			"value": "some value"
		});

		jest.runAllTimers();

		console.log(validationService.onValidateAnswer.mock);
	});
});

```

The store's `onValidateAnswer` never gets called, if I remove the `jest.mock('...');` line from the top it gets called, but then I won't have the mock functions that jest provides.

What I'm trying to test is to see if an action is emitted the store's listener actually gets called.

**Comment by LongLiveCHIEF** [comment]
We don't support jest. Personally, I use mocha, chai, and other tools. Regardless, I don't think there's anything wrong with your Jest setup, there are noted issues with these action listeners not getting called.  (too many to link to),
