### ISSUE TITLE
Replacement for mixins in ES6 style classes

### ISSUE THREAD

**Issue by WizzieP** [reflux/refluxjs#408]
I really love the `Reflux.connect` mixin, but now, when we can't use mixins in ES6 style classes, I am forced to use the way with `unsubscribe`, which is a lot of boilerplate code. What's the current state of support for ES6 style classes?

I would love to contribute if needed.

**Comment by davejacobs** [comment]
Any word on this? I'm curious to see how I can solve this with Reflux?

Fluxxor has an interesting pattern for this: https://github.com/BinaryMuse/fluxxor/pull/117
