### ISSUE TITLE
Reflux utils cause CSP error in Firefox 40

### ISSUE THREAD

**Issue by eanakashima** [reflux/refluxjs#409]
Looks like the [checkEnv](https://github.com/reflux/reflux-core/blob/b291e3dbf897dd61cbc90fdfb377d46f6a6e5a2c/src/utils.js#L14-L20) function in utils does an `eval` to see if certain functions exist in the current environment, and if you use CSP headers that don't allow eval, this will throw an error in Firefox 40 (even with the `try` block wrapping it):

![screen shot 2015-09-01 at 2 27 13 pm](https://cloud.githubusercontent.com/assets/187987/9617061/9c7aa498-50b5-11e5-8cc0-eba466ea177d.png)

I opened an [issue]( https://github.com/reflux/reflux-core/issues/6) to discuss on reflux-core, but since core is a little less interested in browser compatibility, sounds like it's also worth a mention here. Any thoughts on where/how best to handle this?

**Comment by askmatey** [comment]
Similar message in `Firefox OS` (all versions).

> **Applicable CSP Restrictions**
>
> `eval` is disallowed
>    You may not use the eval() function or the eval operator. Both will throw security errors.

See https://developer.mozilla.org/en-US/Apps/Build/Building_apps_for_Firefox_OS/CSP

![firefox-os eval error](https://cloud.githubusercontent.com/assets/812964/10228698/6b2dcca4-6874-11e5-812c-f11a356f030e.png)

**Comment by spoike** [comment]
Sorry about this issue. This will be fixed very soon in core in 0.3.0 as there is a breaking change involved. I'll also publish `reflux` 0.3.0 that will use this fix from `reflux-core`. Hang tight!

**Comment by spoike** [comment]
This is fixed in reflux-core now and by extension reflux 0.3.0.
