### ISSUE TITLE
triggerPromise fails when in node < 0.12 aka when you don't have native promises

### ISSUE THREAD

**Issue by bpeters** [reflux/refluxjs#412]
Currently triggerPromise won't return a promise because the check for promises in reflux-core relies on having a native promise.

```javascript
if (environment.hasPromise) {
    exports.Promise = Promise;
    exports.createPromise = function (resolver) {
        return new exports.Promise(resolver);
    };
} else {
    exports.Promise = null;
    exports.createPromise = function () {};
}
```

I tried to set the Promise library before calling actions: `Reflux.setPromise(require('RSVP'));`

However, when `Reflux` is instantiated the `createPromise` is set and can't be changed, which `triggerPromise` relies on.

I was able to patch it by setting `createPromise` specifically.

```javascript
var Reflux = require('reflux');
var RSVP = require('RSVP');

Reflux.utils.createPromise = function (resolver) {
  return new RSVP.Promise(resolver);
};
```

It works but seems like monkey-patching. I can submit a PR that updates `createPromise` when `setPromise` is called and add some tests.

Thanks!

**Comment by spoike** [comment]
Yes, this is an issue with reflux-core. 

Related issues: reflux/reflux-core#3 and reflux/reflux-core#6

**Comment by LongLiveCHIEF** [comment]
Likewise. I won't be able to get back on the hose until early October.

**Comment by bpeters** [comment]
@spoike @LongLiveCHIEF Okay, will do!

**Comment by spoike** [comment]
Promises have been moved to the [reflux/reflux-promise](https://github.com/reflux/reflux-promise) project.
