### ISSUE TITLE
Support React 0.14

### ISSUE THREAD

**Issue by aaronjensen** [reflux/refluxjs#414]
Didn't see it on a roadmap, so opening an issue here. Is there anything preventing React 0.14 support? (It's currently blocked in the package.json). It is in RC now, so it'd be great if reflux was ready when it released.

**Comment by spoike** [comment]
I haven't looked at the React 0.14 RC yet. I'm not sure if they've removed the mixin support completely, and I really like to use the contextType feature.

You can still use `reflux-core` package instead though if you're not dependent on the React mixin extras, which doesn't have a dependency to react.

**Comment by aaronjensen** [comment]
@spoike They did not, nor will they remove mixin support afaik. The `createClass` syntax is not going away. I'd love to move our app from the mixins, HOC are a better pattern, but it'd be nice if we didn't have to to upgrade.

**Comment by spoike** [comment]
@aaronjensen OK. We can make the react dependency more flexible then in the next 0.2 release if that's the case.

**Comment by soluml** [comment]
Looks like [0.14 is out today](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html).  Any update on this?

**Comment by blainekasten** [comment]
#423
