### ISSUE TITLE
[Question] "Unmounting" a store

### ISSUE THREAD

**Issue by nampas** [reflux/refluxjs#415]
Hey, I have a store that is tied to a particular instance of a React component. When that React component unmounts, I need the store to "unmount" as well. I can't just get rid of my reference to the store though, because it's listening for actions, which keeps a reference to it lying around.

It would be great if there was some way of unregistering action listeners in a store. I was hoping `listenTo` would return some kind of handler that I could use to unregister, but it doesn't. Am I missing something, or is that not possible? If it's not, it seems like a very useful feature.

**Comment by nampas** [comment]
nvrm, looks like I can use `stopListeningToAll()`

**Comment by spoike** [comment]
listenTo actually does return an unregister function, though it is wrapped in an object. https://github.com/reflux/reflux-core/blob/master/src/ListenerMethods.js#L107-L133

```jsx
    var sub = this.listenTo(...);
    // stop the subscription
    sub.stop();
```

It is used internally by `stopListeningTo` and `stopListeningToAll`.
