### ISSUE TITLE
Using triggerPromise I only receive one argument in `.then`?

### ISSUE THREAD

**Issue by ponelat** [reflux/refluxjs#416]
When I have a triggerPromise... I only receive the first argument in `then` clause.

```javascript
var someAction = Reflux.createAction({asyncResult: true});
someAction.listen(function(a,b,c) {
  someAction.completed(a + '-eh', b + '-eh', c + '-eh')
})

someAction.triggerPromise(a,b,c)
  .then(function(d,e,f) { // Assume d,e,f are passed into 
    console.log(d,e,f) // <- Only d is defined
  })
.catch(function() {})
```

I've looked into the source and I'm not sure why this is assumed to be an array of args?... https://github.com/reflux/reflux-core/blob/master/src/PublisherMethods.js#L159

Could be a bug, or it might be me. I can PR if I get some time, but otherwise help is always appreciated!

**Comment by YikaJ** [comment]
I also met this bug just now, it confused me! I am going to merge arguments by stupid way.

**Comment by spoike** [comment]
Moved this to `reflux-promise` project. As the promise functionality has been extracted out of `reflux-core` (and `reflux` by extension)
