### ISSUE TITLE
Completed subaction does not get called

### ISSUE THREAD

**Issue by apreg** [reflux/refluxjs#419]
Here is my action definition:
```
var UserActions = Reflux.createActions({
  loginUser: {asyncResult: true},
  logoutUser: {asyncResult: false}
});
```
If I try to listen to it in a store with ```listenables``` then the ```onLoginUserCompleted``` subaction gets called but what if I don't want to listen to all of the UserActions? I tried ```listenTo``` but with that the subaction did not get called. How could I achieve that?

**Comment by devinivy** [comment]
Hi @apreg– I created some explicit tests for this in reflux-core [here] (https://github.com/reflux/reflux-core/pull/22), and they currently pass.  If this is still an issue.
