### ISSUE TITLE
prevent listening to stores on initialize suggestion

### ISSUE THREAD

**Issue by benrlodge** [reflux/refluxjs#421]
This may not be a reflux specific question, but how I'm implementing my app with it. 

(Using ES6 modules) I have a handful of container components that are importing various stores, though not all modules have been constructed yet - it depends what route you're at. However, as I'm importing the stores at the top of my files, each store is calling its initialize method from the get go, and is running various `this.listenTo` functions. However, I don't want those stores listening until my container component is constructed.

Any suggestion how others are using reflux, or how I should re-organize things to avoid this issue (aside from hacking a custom getter/setter that I'm ready to listen or not)

e.g. (simplified)
```javascript
Container: 
import React, {Component, PropTypes} from 'react';
import HostsStore from '../../stores/hostsStore';
import HostsActions from '../../actions/hostsActions';

class HostsContainer extends Component {

  componentDidMount() {
    this.unsubscribeFromHosts = HostsStore.listen(this.onStatusChange.bind(this));
    HostsActions.loadHosts();
  }
...
```

Store:
```javascript
import Reflux from 'reflux';
import HostsActions from '../actions/hostsActions';

const HostsStore = Reflux.createStore({

  init() {
    this.hosts = [];
    this.listenTo(HostsActions.setParams, this.setParams); // I don't want this running until `HostsContainer` is constructed
  },

```

**Comment by spoike** [comment]
You could let `HostsStore` listen on the `loadHosts` action (or a more specific action that signals that the component is definitely created) and do the `listenTo` wiring there.

```javascript
const HostsStore = Reflux.createStore({
  listenables: [HostsActions],
  onLoadHosts: function() {
    this.listenTo(HostsActions.setParams, this.setParams);
  }
  init () { 
    this.hosts = [];
  },
  /* ... */

});

**Comment by benrlodge** [comment]
perfect thank you - I thought I tried to implement something similar but was getting yelled at for trying to set the listenTo outside of the init, but this works perfect thank you.
