### ISSUE TITLE
How to communicate an action to a React component

### ISSUE THREAD

**Issue by jfairley** [reflux/refluxjs#422]
I asked this question [on StackOverflow](http://stackoverflow.com/questions/32340399/how-to-communicate-an-action-to-a-react-component), but it's not getting much traction. I'm hoping someone here will have an opinion... Sorry in advance for the length.

<br>

While my scenario is pretty specific, I think it speaks to a bigger question in Flux. Components should be simple renderings of data from a store, but what if your component renders a third-party component which is stateful? How does one interact with this third-party component while still obeying the rules of Flux?

So, I have a React app that contains a video player (using [clappr](https://github.com/clappr/clappr)). A good example is seeking. When I click a location on the progress bar, I want to seek the video player. Here is what I have right now. I've tried to strip down my code to the most relevant parts.

```javascript
    var PlayerActions = Reflux.createActions([
        'seek'
    ]);
    
    var PlayerStore = Reflux.createStore({
        listenables: [
            PlayerActions
        ],
    
        onSeek(seekTo) {
            this.data.seekTo = seekTo;
            this.trigger(this.data);
        }
    });
    
    var Player = React.createClass({
        mixins: [Reflux.listenTo(PlayerStore, 'onStoreChange')],
    
        onStoreChange(data) {
            if (data.seekTo !== this.state.seekTo) {
                window.player.seek(data.seekTo);
            }
    
            // apply state
            this.setState(data);
        }

        componentDidMount() {
            // build a player
            window.player = new Clappr.Player({
                source: this.props.sourcePath,
                chromeless: true,
                useDvrControls: true,
                parentId: '#player',
                width: this.props.width
            });
        },

        componentWillUnmount() {
            window.player.destroy();
            window.player = null;
        },

        shouldComponentUpdate() {
            // if React realized we were manipulating DOM, it'd certainly freak out
            return false;
        },

        render() {
            return <div id='player'/>;
        }
    });
```

The bug I have with this code is when you try to seek to the same place twice. Imagine the video player continuously playing. Click on the progress bar to seek. Don't move the mouse, and wait a few seconds. Click on the progress bar again on the same place as before. The value of `data.seekTo` did not change, so `window.player.seek` is not called the second time.

I've considered a few possibilities to solve this, but I'm not sure which is more correct. Input requested...

<br>

___1: Reset `seekTo` after it is used___

Simply resetting `seekTo` seems like the simplest solution, though it's certainly no more elegant. Ultimately, this feels more like a band-aid.

This would be as simple as ...

```javascript
    window.player.on('player_seek', PlayerActions.resetSeek);
```

<br>

___2: Create a separate store that acts more like a pass-through___

Basically, I would listen to a `SeekStore`, but in reality, this would act as a pass-through, making it more like an action that a store. This solution feels like a hack of Flux, but I think it would work.

```javascript
    var PlayerActions = Reflux.createActions([
        'seek'
    ]);
    
    var SeekStore = Reflux.createStore({
        listenables: [
            PlayerActions
        ],
    
        onSeek(seekTo) {
            this.trigger(seekTo);
        }
    });
    
    var Player = React.createClass({
        mixins: [Reflux.listenTo(SeekStore, 'onStoreChange')],
    
        onStoreChange(seekTo) {
            window.player.seek(seekTo);
        }
    });
```

<br>

___3: Interact with `window.player` within my actions___

When I think about it, this _feels_ correct, since calling `window.player.seek` is in fact an action. The only weird bit is that I don't feel right interacting with `window` inside the actions. Maybe that's just an irrational thought, though.

```javascript
    var PlayerActions = Reflux.createActions({
        seek: {asyncResult: true}
    });
    PlayerActions.seek.listen(seekTo => {
        if (window.player) {
            try {
                window.player.seek(seekTo);
                PlayerActions.seek.completed(err);
            } catch (err) {
                PlayerActions.seek.failed(err);
            }
        } else {
            PlayerActions.seek.failed(new Error('player not initialized'));
        }
    });
```

BTW, there's a whole other elephant in the room that I didn't touch on. In all of my examples, the player is stored as `window.player`. Clappr did this automatically in older versions, but though it has since been fixed to work with Browserify, we continue to store it on the `window` (tech debt). Obviously, my third solution is leveraging that fact, which it technically a bad thing to be doing. Anyway, before anyone points that out, understood and noted.

<br>

___4: Seek via `dispatchEvent`___

I also understand that dispatching a custom event would get the job done, but this feels way wrong considering I have Flux in place. This feels like I'm going outside of my Flux architecture to get the job done. I should be able to do it and stay inside the Flux playground.

```javascript
    var PlayerActions = Reflux.createActions({
        seek: {asyncResult: true}
    });
    PlayerActions.seek.listen(seekTo => {
        try {
            let event = new window.CustomEvent('seekEvent', {detail: seekTo});
            window.dispatchEvent(event);
            PlayerActions.seek.completed(err);
        } catch (err) {
            PlayerActions.seek.failed(err);
        }
    });
    
    var Player = React.createClass({
        componentDidMount() {
            window.addEventListener('seekEvent', this.onSeek);
        },
        componentWillUnmount() {
            window.removeEventListener('seekEvent', this.onSeek);
        },
        onSeek(e) {
            window.player.seek(e.detail);
        }
    });
```

**Comment by ce07c3** [comment]
Action => Store => Component that wraps the player, why does that feel like a hack to you?

**Comment by jfairley** [comment]
@ce07c3 
Because of actions like seek. It's a one-shot action. I go through the store, because it's what I'm "supposed to do" but the seek value has no use beyond the immediate flow.

I'll try to walk through the workflow:

Seek-To-5-Sec-Button-Component => Action => Store => Player-Component

1. player is playing.. which means current time updates automatically
1. user clicks the button
1. `Seek-To-5-Sec-Button-Component` calls `Action.seek(5)`
1. `Store` hears action, updates itself, and triggers
1. handler in `Player-Component` reacts to the trigger, calling `this.player.seek(newStoreData.seekValue)`
1. user clicks the button again
1. `Seek-To-5-Sec-Button-Component` calls `Action.seek(5)`
1. `Store` hears action, updates itself
    - dilemma: The seek value is the same this time. Shouldn't I _not_ trigger? The store has not changed. The value was 5. It still remains 5.
    - I know that I need to trigger for this to work, so I trigger anyway.
1. handler in `Player-Component` reacts to the trigger, calling `this.player.seek(newStoreData.seekValue)`
    - Note that I always have to call `this.player.seek`, because it's plausible for "last value" to equal "next value".

So what do we have here?
- A store that always triggers regardless of the value from the action?
- A component that always calls `this.player.seek(...)` whenever the store makes any noise.
- What if the store holds additional data, like current time? A change in current time would trigger a seek. Can't have that.

Maybe your answer is to have a `SeekStore` that _only_ stores this seek value. That way we know every trigger is a legitimate request to seek. Still, it feels like a hack. The only reason we have a store is because we're "supposed to" have a store.

With `Player-Component`, we're not dealing with a component that simply renders data based on the state of a store. It actually contains another completely separate state machine (`this.player`), and interacting with that state machine is awkward.

<br>

To be clear, I'm not necessarily calling this a bug. There are exceptions to any rule, and I can make this work in a variety of ways. I'm merely looking for recommendations that would as closely as possible align with best practices.

**Comment by H3Chief** [comment]
Normally, I would close this question because it doesn't follow our contributing policies... but I think this is something that needs discussion. I'd ask you to take it to the #reactiflux slack, but I'm tired of all the helpful stuff there getting deleted.

I don't really have time to give this the time it deserves at the moment though, but I did want to let you know I have looked at it, and will give it some thought later tonight.

Kneejerk reaction though:  I think sometimes people take the flux pattern and even the reflux pattern a bit too seriously. I tend to keep state that I consider `atomic state` out of my stores entirely, and just handle them within components.  

I define `Atomic State` as any prop that is temporary in nature, and state can be completely lost, without consequences to the app.

**Comment by jfairley** [comment]
@H3Chief, thanks for giving it thought. 

I didn't know about #reactiflux slack, but it looks like they aren't accepting new users right now (according to http://www.reactiflux.com/). I guess a fast-growing community is a good problem to have.

**Comment by ce07c3** [comment]
@jfairley I had "similar" issues with resource stores. Whenever I retrieved a list of resources, it would replace any previously fetched lists - very annoying in case a page has multiple lists of the same resource type.

In this case I'd probably say the player does not need to go to the store. It's a stateful view component built without Flux in mind. One use case where a store could make sense: persist the player's seek position in local storage e.g. by video id (I just leave out URL query parameters for now so this example makes sense).

Videos are a great subject for discussion. Usually, the frequent state updates from stores are "flattened" by the virtual DOM -> DOM diffing and patching. For videos, you might have to include a creator in your actions which you propagate to the components, so that you only update when a user seeks (`this.trigger(state, creator)`).

**Comment by H3Chief** [comment]
+1 to @ce07c3's suggestion.

**Comment by spoike** [comment]
@ce07c3 :+1: 

I'd say you don't need to use Flux if the component is stateful and cohesive (i.e. can do by itself and it's children). That way you have a `Player` component that can be reused. The parent that is using the `Player` could then just wire in actions through it's props if needed. For example:

```JSX
// In the parent (ES6)
import Player from "./Player";
// in render
<Player ref="thePlayer" onSeek={(position) => Actions.seek(position, "thePlayer")} />

// In Player.js
const Player = React.createClass({
    propTypes: { onSeek: React.PropTypes.func },
    // this gets called from within the component:
    _onSeek: function(position) {
      if (this.props.onSeek) { this.props.onSeek(position) }
    }
});
export default Player;

**Comment by jfairley** [comment]
Thanks for the suggestions.

Unfortunately, while the player I'm using is a self-contained, stateful, cohesive component, I've disabled the default controls and am reimplementing my own buttons plus some. My controls go way beyond the typical play-pause / volume / full-screen that you typically see, so using Flux actually is helpful for managing button states... the play-pause button icon, various annotations along the seek bar, the having anything show as disabled when appropriate, etc.

Also, since my React DOM is laid out such that the buttons are not children of the Player component, doing the work with callback functions isn't clean either.

Right now, I'm sitting fine with option #1 "reset seekTo after it is used". I see all the drawbacks, but functionally it works, and I can pretty confidently rely on the player seek action completing more quickly than a user intent on seeking to the same place twice.

I'm also toying with the idea of listening to this action directly in the component. I see this as basically the same as using an event architecture rather than flux, so it doesn't bother me a ton the more I think about it.

**Comment by jfairley** [comment]
@H3Chief, your comment about not taking the flux pattern too seriously keeps bubbling up in my head. It think it most fits my problem and less-than-ideal solutions. I'm glad I have flux in my app, and it simplifies 99% of my workflows, but for those 1% of square-peg-in-a-round-hole scenarios, I'm not sweating it too much. Rather I'm more interested in making it work so I can move on to other tasks. This is more an academic discussion for when my mind wanders at night. :wink:

**Comment by spoike** [comment]
Alternatively you could have two components: `Player` and `PlayerButtons`, the latter taking `Player` as prop from a parent component so it can wire itself up to the player events. Here is an example of using both in the same parent's `render` method:

```JSX
render: () => {
  var player = <Player />;
  return (
    <ParentBase>
      <PlayerButtons player={player}></PlayerButtons>
      <something else="lol" /><hr />
      { player } /* here be the player */
    </ParentBase>
  );
}
```

You can use [`propTypes` to validate](https://facebook.github.io/react/docs/reusable-components.html) the player prop in PlayerButtons:

```JSX
// assuming PlayerButtons is an ES6 Class
PlayerButtons.propTypes = {
  player: React.PropTypes.element // or shape if you want to be more specific with callbacks
};
```

**Comment by jfairley** [comment]
@spoike Interesting suggestion... I've never thought of doing anything with the react component other than returning it to be rendered. I'll try that out.

**Comment by devinivy** [comment]
This was a rich conversation!  It's been a while since there's been any activity here, so I'm going to close this out.  If the conversation wants to continue on (which I hope it does!), please just open a new issue in our new discussion repo and link back to this issue: https://github.com/reflux/discuss
