### ISSUE TITLE
Drop React peer dependency and/or move mixins to another project

### ISSUE THREAD

**Issue by rooftopsparrow** [reflux/refluxjs#434]
Hello refluxjs contributors!

As similarly suggested in issue #423, I'm suggesting that peer dependency be dropped **all together** because there really is no *dependency* on React. Its very much possible that Reflux can be used with or without React. 

In fact, the mixins made specifically for React just return specific function signatures that could be used anywhere. There actually isn't a part of React being used as a peer dependency would suggest. 

Reflux could be used anywhere someone wants to have the benefits of a flux like architecture. I think the library would benefit from not having to drag along a peer dependency. Perhaps another project, like reflux-mixin-react, could enable a peer dependency on a React and Reflux versions to keep the method signatures in React aligned and tested separately for that purpose. 

Anyway, thanks for the great library!

**Comment by spoike** [comment]
The react dependency is dropped in [`reflux-core` project](https://github.com/reflux/reflux-core), all of the functionality that isn't specific to React is moved over there. `reflux` is an extension of the core, with React specifics in it.

AFAIK, other than react `reflux-core` has been extended for [vue](https://www.npmjs.com/package/reflux-vue) and [riot](https://www.npmjs.com/package/reflux-riot).

The peer dependency in the `reflux` npm package is there mostly as a stamp of approval that the mixins will work on those versions of React's API. We should probably rename the `reflux` package to `reflux-react` instead at some point (a lot like how Babel 6 is killing it's `babel` package).

**Comment by rooftopsparrow** [comment]
Ah, very nice. I did not realize the `reflux-core` was there :+1: Thanks for the response and thank you so much for your contributions to the open source community!
