### ISSUE TITLE
Is Refluxjs dying a slow death? 

### ISSUE THREAD

**Issue by mcoetzee** [reflux/refluxjs#436]
First off, thanks for all the work that has already gone into Refluxjs.

We have been using this library since January (2015) and it has worked out well so far. Lately I have been getting concerned with the low level of activity though. As of the writing of this post, the last commit was a month ago. 

Are you guys planning on handing it over to the community, or is there a plan of some sorts for this library?

**Comment by STuFF** [comment]
I would like to have some information too :)
I've started using it for my side projects then import it in our nextgen toolchain at work...
Hope the project is not dying !

**Comment by ce07c3** [comment]
Yeah, lovin' Reflux and don't feel like going the redux way anytime soon :)

**Comment by spoike** [comment]
Sorry about the lack of updates, there is a reason behind those and it's on a personal level since earlier this year. On May I've taken on a side-project that has taken up most of my free time: my newborn son, for which most of my priorities has been rerouted to. This is also why I tend to miss out on discussions on the slack/discourse channel.

As a maintainer I'd still like to work on bugs and new features which has been on my todo list for months, though I need the time and energy for it. For this, it'd be nice with help from the community. If anyone has any ideas, please do let me know.

**Comment by STuFF** [comment]
Well. That's a perfectly fine reason :)
Congratulations for the mother and you, have happy time with no-sleep nights, that's a very time consuming side project, but you'll get tons of <3 for it ;) (I have a 6 old daughter)

**Comment by mcoetzee** [comment]
Thanks for getting back to me and clarifying - big congrats on your newborn son! I totally understand w.r.t. your limited time. How could one help out? It would be great to see your todo list of features - are they under the vNext milestone?

**Comment by spoike** [comment]
@mcoetzee yes, vnext is partly the list. then there are the following as well

* [reflux-core](https://github.com/reflux/reflux-core/issues) has some issues that needs to be taken care of
* Set up a docs site for reflux. See https://github.com/reflux/reflux.github.io

If anyone is interested in contributing, ping me with pull requests and I might make you members in the reflux org.

**Comment by SOSANA** [comment]
Thanks for opening this discussion on this, was going hoping the community wouldn't give up on reflux

**Comment by devinivy** [comment]
Just chiming in– I'm a new collaborator on the project, and I look forward to making some improvements.  By and large it seems to me that reflux is in a stable state, as the codebase is relatively small and its purpose is well-defined.

**Comment by devinivy** [comment]
Closing this out, as the conversation is a bit stale and we have a brand new discussion repo (https://github.com/reflux/discuss)!  So feel free to continue chatting about the state of Reflux over there by opening an issue.  Also, check out the call for maintainers in #447 if you're looking for a way to help with the project.  Cheers!
