### ISSUE TITLE
Reflux mixin dependencies

### ISSUE THREAD

**Issue by chemoish** [reflux/refluxjs#437]
1. Why does mixin order matter—Maybe I am missing something?
2. `listenTo` has a dependency on `connect` is this expected?

``` js
React.createClass({
    mixins: [
        Reflux.connect(Store, 'property'),
        Reflux.listenTo(Store, 'onStoreChange')
    ],

    onStoreChange() {
        console.log(this.state.property.items.length); // 50
    },

    render() {
        console.log(this.state.property.items.length); // 50
    }
});

Reflux.createStore({
    ...

    console.log(items.length); // 50

    this.trigger(items);
});
```

``` js
React.createClass({
    mixins: [
        Reflux.listenTo(Store, 'onStoreChange'),
        Reflux.connect(Store, 'property')
    ],

    onStoreChange() {
        console.log(this.state.property.items.length); // 0
    },

    render() {
        console.log(this.state.property.items.length); // 50
    }
});

Reflux.createStore({
    ...

    console.log(items.length); // 50

    this.trigger(items);
});
```

**Comment by spoike** [comment]
`listenTo` and `connect` mixins weren't designed to be used in tandem... So this is a bug in that regard.

**Comment by chemoish** [comment]
Even if they weren't designed to use in tandem, is that a bad thing?

`connect` provides the `getInitialState()` and `setState()` features and sets up during first render.

`listenTo` provides for subsequent triggers and isn't called during initial mount.

---

Else do you recommend to reimplement `getInitialState()` for components? And manually call `setState()` from `onStoreChange`?

**Comment by MatthewHerbst** [comment]
@chemoish `connect` also sets up listening and calling `setState`. If you use `connect` you don't need `listenTo`.

Note that [mixins are becoming increasingly frowned upon](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html). You should start writing the subscribe/unsubscribes directly into the lifecycle methods of `componentDidMount` and `componentWillUnmount`

**Comment by BryanGrezeszak** [comment]
Considering the move toward ES6 (making mixins lose some relevance) and the age of this issue in general, I'm gonna close it out.
