### ISSUE TITLE
Asynchronous actions error - Uncaught (in promise) Internal Server Error

### ISSUE THREAD

**Issue by benrlodge** [reflux/refluxjs#438]
I'm trying to implement the example in the readme with jQuery promises but am confused how to do so. (I'm using reflux 0.2.13). When trying to use the example below I get the error `Uncaught (in promise) Internal Server Error`

I'm trying to do this -
```javascript
// when 'load' is triggered, call async operation and trigger related actions
Actions.load.listen( function() {
    // By default, the listener is bound to the action
    // so we can access child actions using 'this'
    someAsyncOperation()
        .then( this.completed )
        .catch( this.failed );
});
```

This is my current code.

How do I need to be implementing this (particularly the catch) with what I have below with the `Feedback.submit` method returning my jQuery promise?

```javascript
import Reflux from 'reflux';
import Feedback from '../models/Feedback';

const FeedbackActions = Reflux.createActions([
  { 'sendFeedback': {children: ['completed','failed']} }
]);

FeedbackActions.sendFeedback.listen( function(payload) {  
  const feedback = new Feedback(payload);
  
  feedback.submit()
    .done((data, textStatus, jqXHR) => {
      this.completed(data);
    })
    .fail((jqXHR, textStatus, errorThrown) => {
      this.failed(errorThrown);
    });
  
});

export default FeedbackActions;
```

I tried `feedback.submit().then(...).catch(...)` but that did not work.?

**Comment by spoike** [comment]
jQuery promises aren't supported yet. But I'd be happy to accept a PR that fixes it in [reflux/reflux-promise](https://github.com/reflux/reflux-promise).

**Comment by benrlodge** [comment]
okay thanks, I'll just use Q
