### ISSUE TITLE
Use of 'subscriptions' variable

### ISSUE THREAD

**Issue by charliematters** [reflux/refluxjs#442]
I have a Store which keeps a list of Subscriptions used by the user.

It turns out that subscriptions is a variable added by Reflux.createStore(). This is clashing with my 'subscriptions' array.

Can we keep internal variables protected some way e.g. '_subscriptions'?

**Comment by dtinth** [comment]
None of Reflux’s prototype starts with an underscore, so it should be safe for you to use.

Otherwise, you can hide your internal data completely inside a closure:

```js
const MyStore = (() => {
  const subscriptions = [ ]
  return Reflux.createStore({
    // ...
  })
})()
```

**Comment by devinivy** [comment]
Moved over to reflux-core with https://github.com/reflux/reflux-core/issues/24.
