### ISSUE TITLE
Create TypeScript definitions

### ISSUE THREAD

**Issue by szahn** [reflux/refluxjs#443]
Couldn't find the reflux type definitions in http://definitelytyped.org/tsd/. Would be helpful to have tsd's for those of us who write React in Typescript.

**Comment by szahn** [comment]
A TypeScript guide would also be helpful.

**Comment by devinivy** [comment]
Closing as dupe of #413 .  This would be nice, but I think we'd request help from the community, given that there aren't any maintainers that use TypeScript.
