### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by spoike** [reflux/refluxjs#447]
Due to a change of priorities and busy work days I have to do what most OSS projects do and seek for active maintainers that can bring the project forward and get the ball rolling for more helpful features to be released.

As much as I'd like to put my heart and mind into reflux, there simply is no time for me to do so. However it'd be a shame for me to put this project on indefinite limbo for several reasons:

* The libraries are **still actively used**, with [reflux](https://www.npmjs.com/package/reflux) by itself having more than 11 000 downloads per week on npm.
* Users are generally appreciative for reflux's **super-easy API**, contrary to the other popular flux-but-not-really framework *cough* redux *cough cough*. :wink:

If you have and like to spend some time working on developing reflux and managing the community on github further, let me know on e-mail (check my profile) and we'll take it from there. Contributors who have done PR in the reflux projects are preferred.

**Comment by devinivy** [comment]
:+1: :+1: :bow:

**Comment by ce07c3** [comment]
:+1:

**Comment by devinivy** [comment]
Closing this, but feel free to reach out if you'd like to become involved!
