### ISSUE TITLE
'One page trigger action, another page listenTo' is feasible?

### ISSUE THREAD

**Issue by qinshou** [reflux/refluxjs#449]
There is a form, Each textfield is modified to jump to a new page and return back when data submitted.

PageA
```
class PageA extends React.Component {
	constructor(props) {
		super(props);
	}
	
	componentDidMount() {
		this.listenTo(action.applyChange, function(msg) {
			console.log(msg)
		})
	}
	
	callPageB() {
		this.props.history.replaceState(null, 'pageB');
	}
	
	render() {
		const t = this;
		return (
			<div onClick={t.callPageB.bind(t)}>Enter Data</div>
		)
	}
}
```

PageB
```
class PageB extends React.Component {
	constructor(props) {
		super(props);
		this.state = {text: ''}
	}

	handleSubmit() {
		action.applyChange(this.refs.input.getDOMNode().value);
		this.props.history.replaceState(null, 'pageA');
	}

	render() {
		const t = this;
		return (
			<div>
				<input type="text" ref="input"/>
				<button onClick={t.handleSubmit.bind(t)}>Submit</button>
			</div>
		)
	}
}
```

As is shown above, I've put a listeners to an action in PageA's `componentDidMount()`, It will jump to PageB when user click the 'Enter Data' button. PageB has `action trigger` which is to communicate with submitting data.

Is it feasible and reasonable ? 
This kind of requirement is common, how do you deal with?

**Comment by devinivy** [comment]
If your component uses the `ListenerMixin`, then it should be able to listen to actions fired by other components.  I personally try not to listen for actions in my views, and to only react to changes in stores.  In your case, this would likely mean that a component above both pageA and pageB would have to display one page or the other based upon some piece of data in your stores.

I'm going to close this, but if you feel it's unresolved, we can reopen :+1:

**Comment by qinshou** [comment]
during test I found PageA can't listen any trigger.
 is it because `replaceState` has been executed and jumped? or just bad luck?

**Comment by devinivy** [comment]
Does pageA have the `listenTo` method from the Refluxjs mixin?

**Comment by qinshou** [comment]
I think so, use `reactMixin.onClass(Component, Reflux.connect(require('./store')));`
 and `this` has `listenTo` method
