### ISSUE TITLE
is this project in active development?

### ISSUE THREAD

**Issue by mgenev** [reflux/refluxjs#450]
I evaluating this as a long term commitment and it makes me wonder if it's active. No commits since November. I can't find a way to use ES6 syntax and mixins together. And I'm having an issue with the shouldComponentUpdate and reflux like this:
http://stackoverflow.com/questions/32122567/shouldcomponentupdate-wont-receive-the-newest-state

Even that go around doesn't help....

**Comment by devinivy** [comment]
This project is indeed in development.  Keep in mind that the codebase is relatively small and doesn't need updates incredibly often– additionally most of the code that makes refluxjs tick lives in the reflux-core repo, which has has new updates to master and new PRs.

I've joined as a new collaborator, and I look forward to making some improvements.  It sounds like you have a few issues, some of which seem to be possible bugs and other possible feature requests.  Please feel free to open up separate issues with the details!

**Comment by mgenev** [comment]
Hey, you being  on this project is great news! I remember your work from Waterline and the Hapi plugins

**Comment by devinivy** [comment]
Cheers– I remember you as well.  Nice to see you over here :)

**Comment by qamil** [comment]
@devinivy I'm glad there are new contributors for this project! Hopefully we will see some improvements quickly. I like the library a lot, but #445 is really annoying. Do you know when milestone 0.4.0 is due?

**Comment by devinivy** [comment]
@qamil 0.4.0 is out! See release notes at #459.
