### ISSUE TITLE
No Action files! another step in being super lazy.

### ISSUE THREAD

**Issue by yonatanmn** [reflux/refluxjs#452]
Normally in reflux we have several `Actions` files, containing list of strings, and in the stores we add methods like: `onSomeAction`. we have to manually connect everything, and when we change the name of the Action we do it twice or more.
Usually, I don't share Actions between stores, and this duplication is really annoying. 
So I came up with this:

```
function createStoreAndActions(storeObj) {

    function startWithOn(str) {
        return str[0] === 'o' && str[1] === 'n' && str[2].toUpperCase() === str[2]
    }

    var ActionStrs = Object.keys(storeObj).filter(startWithOn);
    let Actions = reflux.createActions(ActionStrs);

    if (storeObj.listenables) {
        if (Array.isArray(storeObj.listenables)) {
            storeObj.listenables.push(Actions);
        } else {
            storeObj.listenables = [storeObj.listenables, Actions];
        }
    } else {
        storeObj.listenables = Actions;
    }

    return {
        Store: reflux.createStore(storeObj),
        Actions
    }

}
```
the convention I've used is taking all methods starting with 'on' and having capital letter after that. Of course it's easy to implement any other convention (e.g passing to `create` an array of strings etc)
then I can just specify those methods, and an auto actions will be created. 
```
let {Store, Actions} = createStoreAndActions({
    mixins:[...],
     onTestAction(){
       console.log('it is working with no explicit Action!')
    }
});

export {Actions};
export default Store;
```

and in Component:
```
import TestStore, {Actions as testActions} from '../Stores/TestStore';
var Component = React.createClass({
    render: function() {
        return (
          <div onClick={testActions.onTestAction}>click here to log from store</div>
        );
    }
});

**Comment by devinivy** [comment]
Hi @yonatanmn– given that this isn't a bug or feature request, do you mind moving this over to our new discussion repo (https://github.com/reflux/discuss)?

**Comment by yonatanmn** [comment]
Moved, though I wasn't aware of this new Repo, and I guess it's the same for many others...
[here](https://github.com/reflux/discuss/issues/1)

**Comment by devinivy** [comment]
Thanks :)  It's brand new.  I'll try to stop by all the reflux chatrooms to let folks know.
