### ISSUE TITLE
v0.4.0 Release Notes

### ISSUE THREAD

**Issue by devinivy** [reflux/refluxjs#459]
We have released **v0.4.0**.  Here's the rundown!

## Fixes
 - #393 Fixed `isMounted()` warnings.  With React v0.13's deprecation of `isMounted()` we no longer use it.
 
## Breaking Changes
 - #340 Deprecated keyless versions of `connect()` and `connectFilter()`.  This is due to deprecation of React's `replaceState()`, leaving no predictable usage of `connect()` with `setState()`.  See also #242 for further thoughts/explanation.
 - #458 Support React v0.13.0–0.14.x.  That means v0.12.x is no longer supported.  This is meant to match the deprecation of `isMounted()` warnings, and to generally keep things fresh. React v0.15.0 already has a [release candidate](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html), after all!

## Migration Checklist
This shouldn't take terribly long!  For most it will be a small upgrade.  If you're using React v0.12, this upgrade could be more extensive.
 - Ensure you're using React v0.13+ (see [here](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html) and [here](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html)).
 - Update any usage of the keyless version of `Reflux.connect()` and `Reflux.connectFilter()`– i.e. when `Reflux.connect(store)` is called with a single argument.  Instead choose a key in your component state, and connect your store to that– e.g `Reflux.connect(statusStore, 'currentStatus')`.

## Announcements
 - v0.3.1 also came out today.  It is identical to v0.3.0, but its npm distribution now contains a `dist/` folder, thanks to @jmcriffey's contribution and conversation.
 - There's a call for maintainers over at #447 and https://github.com/reflux/reflux-core/issues/19.  There's lots of exciting stuff to work on, including plenty of features, testing, organization, and a Reflux site!
 - We have a new discussion repo for general-purpose reflux chatter and questions.  It's over at [reflux/discuss](https://github.com/reflux/discuss).

Cheers!

**Comment by Asgator** [comment]
Excellent, thx!

**Comment by benknight** [comment]
Are there any release notes for v0.3.0?  We're upgrading from 0.2.12 to 0.4.0

**Comment by devinivy** [comment]
@benknight The only change of note is that promise support is broken-out into the [reflux-promise](https://github.com/reflux/reflux-promise) repo.
