### ISSUE TITLE
can reflux update store in another store?

### ISSUE THREAD

**Issue by aoyunfeng** [reflux/refluxjs#464]
code like
global.TestStore1 = Reflux.createStore({
.......
  onClicka:function(){
        TestStore2.onupdate(value);
  },
.........

**Comment by brettjthom** [comment]
I think you should be able to access the variable like any other variable like
testStore.variable
I have done that from components fine even though it is bad.

Also I think the proper paradigm here is to just make an action and call that.

**Comment by BryanGrezeszak** [comment]
You would use an action to do this, yes.

And currently that does work. You may call an action from basically anywhere, including a store. A store could easily update another store this way.
