### ISSUE TITLE
Many instances have the same structure store

### ISSUE THREAD

**Issue by Flourad** [reflux/refluxjs#465]
For instance, i have instance A, B, C, and i must use separate store for each instance. If the storeA、storeB、storeC are isomorphic, construct three stores has the same structure is redundant.Is there any good ideas to deal with the problem?

**Comment by devinivy** [comment]
I don't understand the issue very well– can you elaborate or be more specific?  Reflux doesn't prescribe a structure for your stores.

**Comment by devinivy** [comment]
If you'd like to continue the conversation about this, please open an issue on [reflux/discuss](https://github.com/reflux/discuss).
