### ISSUE TITLE
mixin is deprecated in React v0.14, what should we do?

### ISSUE THREAD

**Issue by astwyg** [reflux/refluxjs#466]
as we all know, mixin is deprecated in React v0.14, so how should we use Srore in component?

**Comment by jamesmarrs** [comment]
Hey @astwyg, usually theres another way to implement the desired functionality without mixins in reflux, could you provide an example of a problem you are running into?

**Comment by astwyg** [comment]
thanks @jamesmarrs , i am new in reflux, but want to use it, while reading demo with mixin function make me  a little worry.

**Comment by devinivy** [comment]
You can still use the programmatic interface for listening to stores, etc.  See #225 for the future– we'll accept a PR to make refluxjs class-based.  If anyone would like to make a note in the readme about this issue, that would be welcome.
