### ISSUE TITLE
Reflux example for browser without npm

### ISSUE THREAD

**Issue by prakashchokalingam** [reflux/refluxjs#472]
Hi i am tired of searching example of using reflux with react on browser without npm. Most of the examples are written with npm packages.I tried to translate npm codes for browser but it didn't work.Is there any example available or please help me with it .

**Comment by BryanGrezeszak** [comment]
There is a CDN of reflux here: https://cdn.jsdelivr.net/refluxjs/0.4.1/reflux.min.js

Basically everything works the same except instead of having to `require` it in like you would in Node, `Reflux` will just be a global variable you can access.

JSFiddle: https://jsfiddle.net/04eepuue/

**Comment by prakashchokalingam** [comment]
Thanks !
