### ISSUE TITLE
this.listenables on ES6 Store does not listen to child actions

### ISSUE THREAD

**Issue by semikolon** [reflux/refluxjs#478]
So, this.listenables is presented as a shortcut to this.listenToMany() in the readme/documentation

but I found when using Reflux.Store that they're not equivalent. The problem seems to be here: https://github.com/reflux/refluxjs/blob/master/dist/reflux.js#L1390

Why not just use listenToMany directly instead of an implementation of its own like the current code (above)?

**Comment by devinivy** [comment]
@BryanGrezeszak any thoughts on this?

**Comment by BryanGrezeszak** [comment]
Can you tell me in what exact ways you are noticing differences between what is expected and what is seen? I'd like to look into it, but it's hard to look into a bug without that exact info about it.

**Comment by semikolon** [comment]
The child actions aren't being listened to. Can give you code later, but: I
make an action getAll and specify asyncResult: true, then make a listener
getAll and getAllCompleted + ...Failed, in the store. But the completed and
failed children actions do not ever get called, if using this.listenables,
but they do when I use .listenToMany, again this is the callbacks in the
store we're talking about

**Comment by BryanGrezeszak** [comment]
Thanks, that gives me a better idea of what's going on. I'll wait for your example code and use it as the main test case for the issue being solved and get it done.

**Comment by BryanGrezeszak** [comment]
@semikolon - I replicated it and messed with it and you're right on all counts, including the solution. It's one of those situations where you look back in your code and wonder _"why didn't I do it that way in the first place?"_. It's a much better way of going about it. Thanks for finding it, isolating it, and bringing it to our attention.

I'll push soon along with some other things I'm working on.

**Comment by semikolon** [comment]
Hehe :-) Thanks! Happy to have contributed... I was about to write a
failing regression test but never got to it. Anyway, good stuff. I'm
intensely using Reflux now, consulting for a startup, so I really
appreciate any attention payed to issues that pop up. On the whole it's
awesome though!

**Comment by devinivy** [comment]
Good work, yall!  Once this is in I'll make a proper release.

**Comment by semikolon** [comment]
Great! Could you also do a release of reflux-promise? I forked it to merge
two different features from the network, so check that out. Kinda off
topic, sorry

**Comment by BryanGrezeszak** [comment]
I actually had some additions I was going to make. But since you're gonna make it a proper release I'll push it with just bugfixes and you can make a release. Then I'll add those new features later.

**Comment by BryanGrezeszak** [comment]
@devinivy - pull request is up with this change

**Comment by devinivy** [comment]
Great!  Closed by #479.
