### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by kasiriveni** [reflux/refluxjs#483]
the below link is broken http://docs.refluxjs.com/refluxjs-todo/

**Comment by BryanGrezeszak** [comment]
I don't actually see that link anywhere in the docs on here or anything. Where is it from?

**Comment by kasiriveni** [comment]
in https://github.com/reflux/refluxjs#examples Todo Example Project - http://reflux.github.io/refluxjs-todo/

**Comment by BryanGrezeszak** [comment]
Seems the github example itself is intact, just the link to the demo isn't. I'll remove that demo link from my docs in the pull request I have active.

**Comment by kasiriveni** [comment]
okay
