### ISSUE TITLE
0.5.x release

### ISSUE THREAD

**Issue by lszomoru** [reflux/refluxjs#484]
Do you guys have a timeline for the 0.5.x release? Thanks!

**Comment by dodekeract** [comment]
Use reflux-edge if you need it now. It's based on a fork.

**Comment by BryanGrezeszak** [comment]
https://github.com/BryanGrezeszak/reflux-edge

and 

https://www.npmjs.com/package/reflux-edge

and 

https://libraries.io/bower/reflux-edge

I would love for the project to keep going on here, especially since we're just starting to get interest back! But unfortunately I don't control that...

**Comment by BryanGrezeszak** [comment]
Reflux is now updated on git, bower, and npm.

Use it, love it, and let me know about problems. Thanks.
