### ISSUE TITLE
Some questions regarding Actions

### ISSUE THREAD

**Issue by aziz** [reflux/refluxjs#498]
1. I know using `Reflux.__keep.createdActions` I get a list of all actions created. Is there a way to know the name of these actions?

2. Is there a way to define a preEmit hook for all actions?

**Comment by BryanGrezeszak** [comment]
Github issues sections are not for questions like this, they are for issues/problems with RefluxJS.

However, if you post this to StackOverflow and post the link to the question here I'd be glad to answer it for you on there. I just don't want to go around making too much precedent for questions like this in the issues section, as they could easily gum up the real issues and make it difficult to find problems/improve Reflux over time.

**Comment by aziz** [comment]
fair enough, I close this one and here is the link to question on StackOverflow
http://stackoverflow.com/questions/41067093/how-to-get-a-lift-of-all-reflux-actions-names-and-a-preemit-hook-for-all-of-them
