### ISSUE TITLE
reflux use with react-router, store is not run init() when router change back.

### ISSUE THREAD

**Issue by mcdyzg** [reflux/refluxjs#501]
I have two pages: 1.PageOne 2.PageTwo,when i switch to pagetwo from pageone, and then switch back, i found that my PageOne's store doesn't run init().

Here is my code:
 
app.js:

    import React,{Component} from  'react'
    import ReactDOM from 'react-dom'
    import {Router,hashHistory} from 'react-router'

    //page
    import PageOne from '../pages/PageOne'
    import PageTwo from '../pages/PageTwo'

    class App extends Component {
        constructor(props) {
            super(props);
        }

        render() {
            return (
                <div>
                    {this.props.children}
                </div>
            )
        }
    }
    const routes = {
        path: '/',
        component: App,
        indexRoute: {component: PageOne},
        childRoutes: [
            {path: '/pageTwo', component: PageTwo}
        ]
    };
    ReactDOM.render(<Router history={hashHistory} routes={routes}/>, document.getElementById('app'));

store.js(PageOne):

    import { createStore } from 'reflux';
    import Action from './action';

    export default createStore({

        listenables: [Action],

        init() {
            this.state = {
                list:[]
            };
            console.log('init')
        },

        onGetList(){
            const t = this;
            t.state.list = t.state.list.concat([1,2,3]);
            t.trigger(t.state);
        }
    });

action.js(PageOne):

    import Reflux from 'reflux';

	export default Reflux.createActions([
	    'getList',
	]);

## scene
open localhost:8081/#/  first time 

![qq 20161216142403](https://cloud.githubusercontent.com/assets/14190768/21253672/591b0af8-c39b-11e6-94c7-d3b1eedb2b2b.png)

open localhost:8081/#/pageTwo 

![qq 20161216142744](https://cloud.githubusercontent.com/assets/14190768/21253749/d8506f2a-c39b-11e6-9354-e0728750b583.png)

open localhost:8081/#/  second time

![qq 20161216142858](https://cloud.githubusercontent.com/assets/14190768/21253777/0a83cab4-c39c-11e6-97bc-2e640ba9cada.png)

it seems like when switch back to #/, pageOne's store did not run init().

Help me please.

**Comment by BryanGrezeszak** [comment]
I may be confusing something, but I don't see why you would expect it to run `init` again.

`init` is what is called upon creation of the store. Basically like a constructor. At no point in that code is there anything that would destroy the store and then create it again.
