### ISSUE TITLE
Reflux.Component breaks react context propagation

### ISSUE THREAD

**Issue by FalkNisius** [reflux/refluxjs#506]
please add the context param to the constructor, and pass it through the React.Component constructor. The actual implementation in v6.0.0 breaks this.

Some libraries like material-ui move there theming with the context to the components.

instead in Line 45 following  of defineReact.js
`var RefluxComponent = function(props) {
		_extend.call(this, props);
	};`
better
`var RefluxComponent = function(props,context) {
		_extend.call(this, props,context);
	};`

thanks

**Comment by BryanGrezeszak** [comment]
FYI for versioning posterity: it's not that v6 breaks this. It hasn't been implemented at any point.

But yeah, good catch. I'll get this updated to take the extra constructor arguments for components soon.

**Comment by BryanGrezeszak** [comment]
Should be fixed as of v6.2.0
