### ISSUE TITLE
How to stop listening?

### ISSUE THREAD

**Issue by Drikoso** [reflux/refluxjs#508]
This should be a really newbie question, but how can I stop listening to an action? 

 I've been following a video in youtube to learn how to use react with firebase, and the teacher decided to use reflux to manage data flow.  When it comes to the part where my component needs to know when the action of loading my user ends, so I can go to the main screen, the guy in the video binded a listener to the action, using something like this: Actions.loadUser.completed.listen(this.MyMethod.bind(this)).
 Everything worked perfectly, but I don't know how to stop listening to this, and now everytime the load user Action is completed my app goes to the main screen...
 Can someone help me please?

**Comment by BryanGrezeszak** [comment]
Listeners return an unsubscribe. So it should work something like this:

```javascript
var unsub = Actions.loadUser.completed.listen(this.MyMethod.bind(this));

// later
unsub(); // unsubscribes
```

I think this got left out of the new docs...so totally not your fault. I'll get it added into the docs in the next update.

**Comment by Drikoso** [comment]
Thank you very much! :D
