### ISSUE TITLE
Reflux.Component with no store.

### ISSUE THREAD

**Issue by leny** [reflux/refluxjs#509]
Hi, 

I'm not really sure this is really a bug ; in a big project with React + Reflux, I've created a base component from which all my components inherits.

```javascript
class BaseComponent extends Reflux.Component { … }
```

All works OK until I create a component with _no store_ to listen to. By design, reflux [is allowing this](https://github.com/reflux/refluxjs/blob/master/src/defineReact.js#L66-L138). But when the component calls its `componentWillUnmount` method, an Error is thrown because the property `__storeunsubscribes__` isn't an Array (which breaks the [for loop code here](https://github.com/reflux/refluxjs/blob/master/src/defineReact.js#L141-L146)).

The bug can be handled by adding a simple `this.stores = [];` in my base component, but I think this is probably a bug that we can address here in Reflux : if we **can** define a Reflux.Component with _no store_, the `componentWillUnmount` method is broken (I can send a PR to fix that) ; if we **can't** define a Reflux.Component with _no store_, maybe we should raise an error or a warning?

Thanks,

**Comment by BryanGrezeszak** [comment]
It is very much intentional to allow one without a store attached, because that's how `mapStoreToState` works (it's totally separate from the `this.store` concept).

So yes, definitely a bug. And an easy fix, so thanks for pointing it out. I'll have it fixed in the next update.

**Comment by leny** [comment]
Ok. Do you want me to submit a PR for that?

**Comment by BryanGrezeszak** [comment]
@leny - don't worry about it. I already got it fixed and will push the fix live soon.

**Comment by BryanGrezeszak** [comment]
Should now be fix as of v6.1.0, which is now published on here, bower, npm, etc.
