### ISSUE TITLE
React.PureComponent

### ISSUE THREAD

**Issue by timoj** [reflux/refluxjs#514]
It seems that I can't use the purecomponent via reflux. Is there another way to extend my classes with the purecomponent from react other then `extends Reflux.PureComponent`?

**Comment by BryanGrezeszak** [comment]
I've actually been thinking about making a `Reflux.PureComponent`, but it was sorta on the backburner. I'll move it up and see if I can get it done sooner for ya.

**Comment by BryanGrezeszak** [comment]
No idea why I didn't think of this earlier, but you can utilize the static `.extend` method to extend whatever class you want...including `React.PureComponent`.

```javascript
class Example extends Reflux.Component.extend(React.PureComponent)
```

Works perfectly.

I still plan on making the prettier `extends Reflux.PureComponent` version...but for now that'll work wonderfully.

**Comment by BryanGrezeszak** [comment]
`Reflux.PureComponent` should now be in as of v6.3.0.
