### ISSUE TITLE
Looking forward to add some more flexible usage into the doc

### ISSUE THREAD

**Issue by KrisLeeCoder** [reflux/refluxjs#517]
I've read all the docs. It seems that the doc intend to make me combine Stores and Components with STATE. But I don't think it's flexible. In v2.x, I can use a receiver in React Components, and send data in Stores with method "trigger". In this way,  I can deal with the data in the receiver, like formatting or filtering it, or trigger another action. the code may like this:
```
class MyComponent extends React.Component {
  constructor(props){}
  componentDidMount(){
    this.unsubscribe = MyStore.listen(this.onStoreChange.bind(this));
    MyAction.someAction();
  }
  onStoreChange(data) {
    // data is {loading: true}
    // do something with data, calling this.setState is up to the developer
  }
}

MyAction = Reflux.createAction("someAction");
MyAction.listen(() => {
    // do something
});

MyStore = Reflux.createStore({
  listenables: [MyAction, ],
  someAction: () => {
    this.trigger({loading: true});
  }
}
```

So confused, why not put this style in the doc and make it more flexible to use?

**Comment by BryanGrezeszak** [comment]
Seems like you're describing [`mapStoreToState`](https://github.com/reflux/refluxjs/blob/f295a9b50004e380e0cf0fd5c99552a27bb6b2ae/docs/components/README.md#manually-mapping-states-with-thismapstoretostate) literally to a tee.

It's completely up to the coder what gets passed to the component, how it's filtered, formatted, whether you call other stuff, etc. And if you just map an empty object then no `setState` is called at all.
