### ISSUE TITLE
How to JUST receive one actions's data in components

### ISSUE THREAD

**Issue by KrisLeeCoder** [reflux/refluxjs#518]
Component : `loginFom`.
Store: `UserStore`, both `login` and `register` actions are listened in it.
Actions: `login`, with children `completed` and `failed`; `register`, with children `completed` and `failed`.
The `login` and `register` action will send a ajax request, and call `completed` if request succeed with user's data, or call `failed` with the error message.
In loginForm component, I just need the `login.success` action's returned data.

So, HOW can I use store in react components without dealing with the whole triggered data? 
Or, HOW can I just receive one method's triggered data from store in components?

**Comment by BryanGrezeszak** [comment]
Components don't care about receiving actions. They dispatch them. It goes:

`component -> action -> store -> back to component again`

So the relevant question is the _"So, HOW can I use store in react components without dealing with the whole triggered data?"_

There are multiple ways of dealing with that.

There's [`storeKeys`](https://github.com/reflux/refluxjs/tree/master/docs/components#limiting-mixing-with-thisstorekeys) for normal declarative style usage to filter out all but just the store properties you want.

And for more imperative/manual usage, you use [`mapStoreToState`](https://github.com/reflux/refluxjs/tree/master/docs/components#manually-mapping-states-with-thismapstoretostate) to filter as well as format what parts of a store's state go into your component.
