### ISSUE TITLE
Add support for eventstream-like objects

### ISSUE THREAD

**Issue by spoike** [reflux/refluxjs#52]
Add support for listening to eventstream like objects. E.g. eventstreams from [bacon.js](https://github.com/baconjs/bacon.js) or [event-stream](https://github.com/dominictarr/event-stream). 

Under the hood we only need to check if the listenable object has a map function (which means also arrays may be listened to as well).

## Motivating example

You will now be able to simply create eventstreams to be used as "automatic" actions or stores. E.g. `resize` event in bacon.js:

```javascript
var resizeStream = $(window).asEventStream('resize');

var ResizeComponent = React.createClass({
    mixins: [Reflux.ListenerMixin],
    componentDidMount: function() {
        this.listenTo(resizeStream, this.onAppResize);
    },
    onAppResize: function() {
       // is called everytime the window resizes
    },
    render: function() { /* ... */ }
});
```

Thoughts?

**Comment by breandr** [comment]
@spoike I would love to see the rxjs example in the README. :)

**Comment by breandr** [comment]
Is there an example on how to do this with Bacon or RxJs with the latest reflux?

**Comment by LongLiveCHIEF** [comment]
Keep an eye on the v0.3 branch. Hoping to have the alpha release finished by the end of this coming weekend.
