### ISSUE TITLE
How can I change the store state without setting the component state?

### ISSUE THREAD

**Issue by lyd600lty** [reflux/refluxjs#521]
I call an action in the component `componentWillUnmount` function, but when set the store state,
the component is unmount, so the error happened like following.

![image](https://cloud.githubusercontent.com/assets/2917899/24031992/a53ccdf0-0b20-11e7-9de0-0120681c0c83.png)

**Comment by BryanGrezeszak** [comment]
Most likely you'll need to look at [this section](https://github.com/reflux/refluxjs/tree/master/docs/components#componentwillmount-and-componentwillunmount) of the docs.

That's probably what's causing it.
