### ISSUE TITLE
npm WARN reflux@6.4.1 requires a peer of react@^15.0.2 but none was installed.

### ISSUE THREAD

**Issue by bossno1** [reflux/refluxjs#529]
"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.2",
		"reflux": "^6.4.1"
	},
please help,thanks

**Comment by kriscarle** [comment]
Hi @bossno1 

That is a normal warning telling you that Reflux needs React version 15. You are using an alpha version of React 16. Unless you absolutely need to experiment with React 16, I would recommend sticking with a stable version of React 15. 

Libraries like Reflux will lag behind the bleeding edge React code, understandably so, as it often takes a lot of effort to upgrade and it is better to wait for the new version to be stable. If you really need to use React 16 now you will likely need to fork and try to upgrade libraries like Reflux yourself. If all goes well you can submit it back here as a PR. 

Best of luck learning React and React Native :)

(Also I'm not an owner/member here, just a fan trying to help out :) )

**Comment by bossno1** [comment]
thanks!
