### ISSUE TITLE
Support of React.js v16

### ISSUE THREAD

**Issue by believer-ufa** [reflux/refluxjs#534]
Hello and thanks for this nice library!

Can i ask: you will support new React.js? As i see, currently it is not working with React.js v16.

**Comment by eek** [comment]
We're using Reflux with React v16 without any issues since it came out. What problem do you have?

**Comment by believer-ufa** [comment]
Nice to hear it) Then the problem is somewhere in my code

**Comment by samfahmie** [comment]
Refluxjs has a dependency on React 15. NPM refuses to install React 16 while I have Reflux installed because it doesn't meet the peer dependency.

**Comment by ied3vil** [comment]
Probably not relevant still, but i have started to port reflux for react16 so it works with no warns on an upgraded react15->16 project. It is a huge project and the upgrade has to be done gradually.

https://www.npmjs.com/package/reflux-react-16

**Comment by andpor** [comment]
Why is this CLOSED ? Reflux 6.4.1 has React 15 dependency and React 16 cannot be used....????????

**Comment by ied3vil** [comment]
@andpor see the reply above... react 16 compatible package above, we are using it in production with no issues however it s just set for compatibility we are not doing development on it
