### ISSUE TITLE
Roadmap questions

### ISSUE THREAD

**Issue by LiangZugeng** [reflux/refluxjs#550]
This is a question rather than a issue or feature request.

We've been using Reflux in our React SPA Web application since from Jan 2017, it's been heavily used in almost every single page in our application and it became one of the most important library in our tech stack.

As we are planning our tech roadmap for the next year, we wonder if there is a development plan for Reflux, we are upgrading to React 16.x but found Reflux requires 15.x (no problems working with 16.x though), so if anyone can share some insights regarding how Reflux will be further developed and maintained, it will help us make some decisions.

Thanks a lot in advance.

**Comment by LiangZugeng** [comment]
@spoike care to share some info?

**Comment by eek** [comment]
I think the first important step is for @spoike &/ @krawaller to select one or multiple contributors that would take this project forward. 

Maybe we can make another issue with people that are interested to take this into their hands, and then to appoint them as Contributors.

cc @LiangZugeng, cc @ied3vil (from which I've also seen some activity)

Maybe you guys can be the first new contributors.

**Comment by ied3vil** [comment]
@LiangZugeng if you plan to use reflux with react16 you can safely use my ported package and even contribute if you want to port the tests or improve - i've upgraded the build scripts to webpack since grunt was a no choice

here you go: https://www.npmjs.com/package/reflux-react-16

**Comment by lloydjatkinson** [comment]
Perhaps a migration guide to other libraries is needed.

https://www.fin.com/posts/from-reflux-to-redux/

**Comment by LiangZugeng** [comment]
We moved to mobx, issue closed.
