### ISSUE TITLE
Component reusability

### ISSUE THREAD

**Issue by andwaal** [reflux/refluxjs#62]
Hi, how would one reuse a component using the (Re)flux architecture?

For instance the ToDo example, what if I would like to have multiple instances of ToDo lists on a page`( Todo today, todo tomorrow etc).
Because of the singleton nature of the Actions(dispatchers) all Todo`s would be updated on all actions triggered.

**Comment by hipertracker** [comment]
What if you just **do not know** how many instances of the component can used in the application? Hardcoding all possible usage cases inside the store, with assigned arbitrary key names is obviously the **anti-pattern**.
